version: "3"

services:

  scylla-node1:
    container_name: cassandra
    image: scylladb/scylla:4.1.0
    restart: always
    command: --seeds=scylla-node1 --smp 1 --memory 750M --overprovisioned 1 --api-address 172.22.0.6
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    ports:
      - 9042:9042
    networks:
      kafka_copernico_net:
        ipv4_address: 172.22.0.6

networks:
  kafka_copernico_net:
    external:
      name: kafka_copernico_net