package design_principles.microservice.kafka_consumer_microservice

import design_principles.microservice.Microservice

trait KafkaConsumerMicroservice extends Microservice[KafkaConsumerMicroserviceRequirements]
