
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-apps-http
  labels:
    k8s-apps: http
spec:
  selector:
    matchLabels:
      app: readside-cluster
  namespaceSelector:
    matchNames:
      - copernico
  endpoints:
    - port: monitoring
      interval: 15s