{
 "title": "Sujeto",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Messages Lost",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(copernico_histograms_bucket{entity=\"actor-transaction-_sujeto_tributario_transaction-latency\",  le=\"100000.0\"}) - sum(copernico_counters_total{entity=\"SujetoTributarioTransactionSuccessCounter\"}) "
    }
   ]
  },
  {
   "title": "SujetoTributarioTransactionSuccessCounter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "copernico_counters_total{entity=\"SujetoTributarioTransactionSuccessCounter\"} "
    }
   ]
  },
  {
   "title": "sujeto_tributario_transaction-latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "copernico_histograms_bucket{entity=\"actor-transaction-_sujeto_tributario_transaction-latency\"}"
    }
   ]
  }
 ]
}