scrape_configs:
  - job_name: akkaKamon
    scrape_interval: 5s
    static_configs:
      - targets:
          - 0.0.0.0:9095
          - 0.0.0.0:5000
          - 0.0.0.0:5001
          - 0.0.0.0:5002