scrape_configs:
  - job_name: akkaKamon
    scrape_interval: 5s
    static_configs:
      - targets:
          - host.docker.internal:9095
          - host.docker.internal:5000
          - host.docker.internal:5001
          - host.docker.internal:5002
          - host.docker.internal:5003
          - host.docker.internal:5004
          - host.docker.internal:5005
          - host.docker.internal:5006
