package consumers_spec.no_registrales.sujeto

import consumers_spec.no_registrales.testsuite.NoRegistralesTestSuiteAcceptance
import org.scalatest.Ignore

@Ignore
class SujetoSpecAcceptance extends SujetoSpec with NoRegistralesTestSuiteAcceptance
