---
version: '2.4'

services:

  cassandra:
    container_name: cassandra
    image: cassandra
    volumes:
      - ../cassandra/config/cassandra.yaml:/etc/cassandra/cassandra.yaml
    ports:
      - 9042:9042

  zookeeper:
    container_name: zookeeper
    image:  confluentinc/cp-zookeeper:5.3.0
    ports:
      - 2181:2181 # this is to test the kafka-consumer
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka: # https://github.com/confluentinc/schema-registry/issues/689#issuecomment-416315907
    container_name: kafka
    image:  confluentinc/cp-enterprise-kafka:5.3.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  grafana:
    build: '../grafana'
    container_name: grafana
    network_mode: ${NETWORK_MODE}
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: ${NETWORK_MODE}
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
