{
 "title": "DGR-COP-SUJETO_TRI",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 }, "options": { "content": "# writeside\n\n" }, "content": "\n# WRITESIDE\n\n\n\n\n" },
  { "type": "text", "gridPos": { "h": 2, "w": 4, "x": 15, "y": 0 }, "options": { "content": "# readside\n\n" }, "content": "\n# READSIDE\n\n\n\n\n" },
  {
   "title": "latencia akka",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "\nhistogram_quantile(0.9, \n  rate(copernico_histograms_bucket{entity=\"actor-transaction-sujeto_tributario_transaction-latency\"}[5m])\n)\n",
     "legendFormat": "actor-transaction-_obligacion_tributaria_transaction-latency"
    }
   ]
  },
  {
   "title": "Cassandra projections per minute (RPM)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 13, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\n\nsum(\nincrease(copernico_counters_total{entity=\"projection-handler-sujeto_projection_handler-request\"}[1m])\n)\n"
    }
   ]
  },
  {
   "title": "TOTAL TRANSACTIONS ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{entity=\"actor-transaction-sujeto_tributario_transaction-request\"} )\n"
    }
   ]
  },
  {
   "title": "latencia cassandra",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "copernico_histograms_bucket{le=\"3000.0\",entity=\"projection-handler-sujeto_projection_handler-latency\"}",
     "legendFormat": "actor-transaction-_obligacion_tributaria_transaction-latency"
    }
   ]
  },
  {
   "title": "TOTAL EVENTS PERSISTED ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{entity=\"SujetoActor-persisted-SujetoUpdatedFromTri\"} )\n"
    }
   ]
  },
  {
   "title": "Kafka consumptions per minute (RPM)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\nsum(\nincrease(copernico_counters_total{entity=\"actor-transaction-sujeto_tributario_transaction-request\"}[1m])\n)\n"
    }
   ]
  },
  {
   "title": "TOTAL PROJECTIONS ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(copernico_counters_total{entity=\"projection-handler-sujeto_projection_handler-request\"} )"
    }
   ]
  },
  {
   "title": "TOTAL PROJECTIONS PER NODE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "copernico_counters_total{entity=\"projection-handler-sujeto_projection_handler-request\"} "
    }
   ]
  },
  {
   "title": "Persistencias per minute (RPM)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\nsum(\nincrease(copernico_counters_total{entity=\"SujetoActor-persisted-SujetoUpdatedFromTri\"}[1m])\n)\n"
    }
   ]
  },
  {
   "title": "TOTAL TRANSACTIONS PER NODE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "copernico_counters_total{entity=\"actor-transaction-sujeto_tributario_transaction-request\"} \n"
    }
   ]
  },
  {
   "title": "PERSISTENCIAS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "copernico_counters_total{entity=\"SujetoActor-persisted-SujetoUpdatedFromTri\"} "
    }
   ]
  }
 ]
}