{
 "title": "DGR-COP-OBLIGACIONES_TRI",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Transactions Per Minute (RPM)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\nsum(\nincrease(copernico_counters_total{entity=\"actor-transaction-obligacion_tributaria_transaction-request\"}[1m])\n)\n"
    }
   ]
  },
  {
   "title": "LATENCIA",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(\nhistogram_quantile(0.9, \n  rate(copernico_histograms_bucket{entity=\"actor-transaction-obligacion_tributaria_transaction-latency\"}[5m])\n)\n)",
     "legendFormat": "actor-transaction-_obligacion_tributaria_transaction-latency"
    }
   ]
  },
  {
   "title": "TRANSACCIONES",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "copernico_counters_total{entity=\"actor-transaction-obligacion_tributaria_transaction-request\"} \n"
    }
   ]
  },
  {
   "title": "PERSISTENCIAS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "copernico_counters_total{entity=\"ObligacionActor-persisted-ObligacionPersistedSnapshot\"} "
    }
   ]
  }
 ]
}