apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpc-app-deployment
spec:
  selector:
    matchLabels:
      app: rpc-app
  replicas: 2
  template:
    metadata:
      labels:
        app: rpc-app
    spec:
      containers:
        - name: rpc-app-cont
          image: supergiantkir/prometheus-test-app
          ports:
            - name: web
              containerPort: 8081