apiVersion: v1
kind: Service
metadata:
  name: rpc-app-service
  labels:
    app: rpc-app
spec:
  ports:
    - name: web
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: rpc-app