package consumers_spec.no_registrales.cotitularidad

import consumers_spec.no_registrales.testsuite.NoRegistralesTestSuiteAcceptance
import org.scalatest.Ignore

@Ignore
class CotitularidadSpecAcceptance extends CotitularidadSpec with NoRegistralesTestSuiteAcceptance
