package consumers_spec.no_registrales.cotitularidad

import consumers_spec.no_registrales.testsuite.NoRegistralesTestSuiteMock

class CotitularidadSpecUT extends CotitularidadSpec with NoRegistralesTestSuiteMock
